version: "3"
services:
  redis:
    image: arm32v6/redis:5-alpine
    ports:
      - 6379:6379
  kinesis:
    build:
      context: kinesis
      dockerfile: Dockerfile-raspbian
    volumes:
      - /neochi/neochi-core/src/neochi:/code/neochi
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
  ir_receiver:
    build:
      context: ir_receiver
      dockerfile: Dockerfile-raspbian
    volumes:
      - /neochi/data/ir:/data # リモコン信号ファイルの保存先。/dataはアプリ内でハードコードされているので注意
      - /neochi/neochi-core/src/neochi:/code/neochi # coreモジュールのマウント
      - /neochi/ir_receiver/src/logs:/code/logs # logファイルのマウント
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: "host"
    depends_on:
      - redis